### PR TITLE
Melbourne page

### PR DESCRIPTION
**Pull request by nikkirubinstein**
I have added a Melbourne page and included a pin for Melbourne on the global page

### CODE REVIEW

**Comment by philippbayer** [comment]
@DamienIrving Is the usual approach now to add @nikkirubinstein as a collaborator and merge this PR?

**Comment by DamienIrving** [comment]
@philippbayer - Yep. Will do that now

**Comment by philippbayer** [comment]
Thank you! I can do the same for the next PRs

**Comment by nikkirubinstein** [comment]
Thanks @DamienIrving and @philippbayer :smile:

**Comment by philippbayer** [comment]
No worries @nikkirubinstein! Damien should've added you as a collaborator by now so you don't have to send pull requests anymore, you can directly push to this resbaz/resbaz2018 repository

**Pull request merged**
